import { TopicModule, CompanyHiringTrack, UserProfile } from './types';

export const INITIAL_USER: UserProfile = {
  name: 'Aditi Sharma',
  role: 'B.Tech Computer Science • Class of 2025',
  targetGoal: 'Aiming for Tier-1 Product Companies',
  overallReadiness: 68,
  dsaReadiness: 80,
  systemAptitudeReadiness: 40,
  solvedCount: 142,
  streakDays: 14,
  mocksDone: 8,
  avatarUrl: 'https://lh3.googleusercontent.com/aida/AEtjO1XJn3YHNVSAtPmej-4QUlLsMavJsJOIs_DDJkUnq8ejYMlexCZpcMzTn8-t8vpJ141d1YazmgvvbfBEV2hmW3BAmrtEQVfhic9tY0uu1N_WcwaigqwBVFNwSN4rD8adk2Gamr4xpQF_E7iusuljSk6CNv_FNgg3c40bd5Ezp2yF1k5_OY0rP6UEshFRozPU7ABZs4Bjx-dPGVfRJ8rCNX7sk8vIceNEzjRr0-G78Z9lHbTEw2gu6qz4gk4',
  email: 'aditi.sharma@campus.edu',
  subscriptionTier: 'Pro',
  planRenewal: 'Renews Dec 2025 • Manage billing, perks',
};

export const TOPIC_MODULES: TopicModule[] = [
  {
    id: 'arrays-hashing',
    title: 'Arrays & Hashing',
    track: 'dsa',
    badge: 'Foundational • 12 Problems',
    badgeType: 'default',
    totalProblems: 12,
    completedProblems: 8,
    companies: ['Google', 'Amazon', 'Microsoft', 'Uber'],
    description: 'Fundamental memory patterns, constant-time lookups, and contiguous sequence optimizations.',
    estHoursRemaining: 3.5,
    avgAccuracy: 84,
    problems: [
      {
        id: 'two-sum',
        number: 1,
        title: 'Two Sum',
        difficulty: 'Easy',
        tag: 'Hash Map',
        accuracy: '91% Acc.',
        status: 'solved',
        companies: ['Google', 'Amazon', 'Apple'],
        description: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice.',
        examples: [
          { input: 'nums = [2,7,11,15], target = 9', output: '[0,1]', explanation: 'Because nums[0] + nums[1] == 9, we return [0, 1].' },
          { input: 'nums = [3,2,4], target = 6', output: '[1,2]' },
        ],
        starterCode: {
          python: `class Solution:\n    def twoSum(self, nums: list[int], target: int) -> list[int]:\n        seen = {}\n        for i, n in enumerate(nums):\n            diff = target - n\n            if diff in seen:\n                return [seen[diff], i]\n            seen[n] = i\n        return []`,
          java: `class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int diff = target - nums[i];\n            if (map.containsKey(diff)) return new int[]{map.get(diff), i};\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}`,
          cpp: `class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        unordered_map<int, int> seen;\n        for (int i = 0; i < nums.size(); ++i) {\n            int diff = target - nums[i];\n            if (seen.count(diff)) return {seen[diff], i};\n            seen[nums[i]] = i;\n        }\n        return {};\n    }\n};`,
        },
        solutionHint: 'Use a Hash Table to keep track of complements in O(n) single pass time complexity.',
      },
      {
        id: 'valid-anagram',
        number: 2,
        title: 'Valid Anagram',
        difficulty: 'Easy',
        tag: 'Frequency Array',
        accuracy: '88% Acc.',
        status: 'solved',
        companies: ['Uber', 'Google', 'Meta'],
        description: 'Given two strings s and t, return true if t is an anagram of s, and false otherwise. An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase.',
        examples: [
          { input: 's = "anagram", t = "nagaram"', output: 'true' },
          { input: 's = "rat", t = "car"', output: 'false' },
        ],
        starterCode: {
          python: `class Solution:\n    def isAnagram(self, s: str, t: str) -> bool:\n        if len(s) != len(t): return False\n        count = [0] * 26\n        for c1, c2 in zip(s, t):\n            count[ord(c1) - ord('a')] += 1\n            count[ord(c2) - ord('a')] -= 1\n        return all(x == 0 for x in count)`,
          java: `class Solution {\n    public boolean isAnagram(String s, String t) {\n        if (s.length() != t.length()) return false;\n        int[] count = new int[26];\n        for (char c : s.toCharArray()) count[c - 'a']++;\n        for (char c : t.toCharArray()) if (--count[c - 'a'] < 0) return false;\n        return true;\n    }\n}`,
          cpp: `class Solution {\npublic:\n    bool isAnagram(string s, string t) {\n        if (s.size() != t.size()) return false;\n        int count[26] = {0};\n        for (char c : s) count[c - 'a']++;\n        for (char c : t) if (--count[c - 'a'] < 0) return false;\n        return true;\n    }\n};`,
        },
        solutionHint: 'Count character frequencies with an integer array of size 26 or a hash map.',
      },
      {
        id: 'group-anagrams',
        number: 3,
        title: 'Group Anagrams',
        difficulty: 'Medium',
        tag: 'Sorting & Hashing',
        accuracy: '76% Acc.',
        status: 'solved',
        companies: ['Amazon', 'Microsoft', 'Goldman Sachs'],
        description: 'Given an array of strings strs, group the anagrams together. You can return the answer in any order.',
        examples: [
          { input: 'strs = ["eat","tea","tan","ate","nat","bat"]', output: '[["bat"],["nat","tan"],["ate","eat","tea"]]' },
        ],
        starterCode: {
          python: `class Solution:\n    def groupAnagrams(self, strs: list[str]) -> list[list[str]]:\n        from collections import defaultdict\n        res = defaultdict(list)\n        for s in strs:\n            res[tuple(sorted(s))].append(s)\n        return list(res.values())`,
          java: `class Solution {\n    public List<List<String>> groupAnagrams(String[] strs) {\n        Map<String, List<String>> map = new HashMap<>();\n        for (String s : strs) {\n            char[] ca = s.toCharArray();\n            Arrays.sort(ca);\n            String key = String.valueOf(ca);\n            map.computeIfAbsent(key, k -> new ArrayList<>()).add(s);\n        }\n        return new ArrayList<>(map.values());\n    }\n}`,
          cpp: `class Solution {\npublic:\n    vector<vector<string>> groupAnagrams(vector<string>& strs) {\n        unordered_map<string, vector<string>> mp;\n        for (auto& s : strs) {\n            string key = s;\n            sort(key.begin(), key.end());\n            mp[key].push_back(s);\n        }\n        vector<vector<string>> ans;\n        for (auto& p : mp) ans.push_back(p.second);\n        return ans;\n    }\n};`,
        },
        solutionHint: 'Represent character anagram keys either by alphabetical sorting or tuple counts.',
      },
      {
        id: 'top-k-frequent-elements',
        number: 4,
        title: 'Top K Frequent Elements',
        difficulty: 'Medium',
        tag: 'Bucket Sort / Heap',
        accuracy: '69% Acc.',
        status: 'solved',
        companies: ['Amazon', 'Facebook', 'Bloomberg'],
        description: 'Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order. The time complexity must be better than O(n log n).',
        examples: [
          { input: 'nums = [1,1,1,2,2,3], k = 2', output: '[1,2]' },
        ],
        starterCode: {
          python: `class Solution:\n    def topKFrequent(self, nums: list[int], k: int) -> list[int]:\n        count = Counter(nums)\n        buckets = [[] for _ in range(len(nums) + 1)]\n        for n, c in count.items():\n            buckets[c].append(n)\n        res = []\n        for i in range(len(buckets) - 1, 0, -1):\n            for n in buckets[i]:\n                res.append(n)\n                if len(res) == k: return res\n        return res`,
          java: `class Solution {\n    public int[] topKFrequent(int[] nums, int k) {\n        // O(n) bucket sort implementation\n        return new int[0];\n    }\n}`,
          cpp: `class Solution {\npublic:\n    vector<int> topKFrequent(vector<int>& nums, int k) {\n        // Bucket sort logic\n        return {};\n    }\n};`,
        },
        solutionHint: 'Use Bucket Sort indexed by frequency for an optimal O(n) runtime.',
      },
      {
        id: 'product-of-array-except-self',
        number: 5,
        title: 'Product of Array Except Self',
        difficulty: 'Medium',
        tag: 'Prefix Products',
        accuracy: '72% Acc.',
        status: 'solved',
        companies: ['Amazon', 'Apple', 'LinkedIn'],
        description: 'Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i]. Must run in O(n) time and without using the division operator.',
        examples: [
          { input: 'nums = [1,2,3,4]', output: '[24,12,8,6]' },
        ],
        starterCode: {
          python: `class Solution:\n    def productExceptSelf(self, nums: list[int]) -> list[int]:\n        res = [1] * len(nums)\n        prefix = 1\n        for i in range(len(nums)):\n            res[i] = prefix\n            prefix *= nums[i]\n        postfix = 1\n        for i in range(len(nums) - 1, -1, -1):\n            res[i] *= postfix\n            postfix *= nums[i]\n        return res`,
          java: `class Solution {\n    public int[] productExceptSelf(int[] nums) {\n        int n = nums.length;\n        int[] res = new int[n];\n        int p = 1;\n        for(int i=0; i<n; i++) { res[i] = p; p *= nums[i]; }\n        int post = 1;\n        for(int i=n-1; i>=0; i--) { res[i] *= post; post *= nums[i]; }\n        return res;\n    }\n}`,
          cpp: `class Solution {\npublic:\n    vector<int> productExceptSelf(vector<int>& nums) {\n        int n = nums.size();\n        vector<int> res(n, 1);\n        int p = 1;\n        for(int i=0; i<n; ++i) { res[i] = p; p *= nums[i]; }\n        int post = 1;\n        for(int i=n-1; i>=0; --i) { res[i] *= post; post *= nums[i]; }\n        return res;\n    }\n};`,
        },
        solutionHint: 'Calculate prefixes left-to-right into the output array, then accumulate suffixes in reverse.',
      },
      {
        id: 'longest-consecutive-sequence',
        number: 6,
        title: 'Longest Consecutive Sequence',
        difficulty: 'Medium',
        tag: 'Hash Set',
        accuracy: '62% Acc.',
        status: 'in-progress',
        companies: ['Amazon', 'Google', 'Spotify'],
        description: 'Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence. You must write an algorithm that runs in O(n) time.',
        examples: [
          { input: 'nums = [100,4,200,1,3,2]', output: '4', explanation: 'The longest consecutive elements sequence is [1, 2, 3, 4]. Therefore its length is 4.' },
        ],
        starterCode: {
          python: `class Solution:\n    def longestConsecutive(self, nums: list[int]) -> int:\n        num_set = set(nums)\n        longest = 0\n        for n in num_set:\n            if (n - 1) not in num_set:\n                length = 1\n                while (n + length) in num_set:\n                    length += 1\n                longest = max(longest, length)\n        return longest`,
          java: `class Solution {\n    public int longestConsecutive(int[] nums) {\n        Set<Integer> set = new HashSet<>();\n        for (int n : nums) set.add(n);\n        int maxLen = 0;\n        for (int n : set) {\n            if (!set.contains(n - 1)) {\n                int cur = n, len = 1;\n                while (set.contains(cur + 1)) { cur++; len++; }\n                maxLen = Math.max(maxLen, len);\n            }\n        }\n        return maxLen;\n    }\n}`,
          cpp: `class Solution {\npublic:\n    int longestConsecutive(vector<int>& nums) {\n        unordered_set<int> st(nums.begin(), nums.end());\n        int ans = 0;\n        for (int x : st) {\n            if (!st.count(x - 1)) {\n                int y = x + 1;\n                while (st.count(y)) y++;\n                ans = max(ans, y - x);\n            }\n        }\n        return ans;\n    }\n};`,
        },
        solutionHint: 'Only start counting streaks when (n - 1) is not in the set, ensuring each element is visited at most twice.',
      },
      {
        id: 'encode-and-decode-strings',
        number: 7,
        title: 'Encode and Decode Strings',
        difficulty: 'Medium',
        tag: 'String Manipulation',
        accuracy: '54% Acc.',
        status: 'pending',
        companies: ['Uber', 'Google', 'Meta'],
        description: 'Design an algorithm to encode a list of strings to a string. The encoded string is then sent over the network and is decoded back to the original list of strings.',
        examples: [
          { input: 'strs = ["lint","code","love","you"]', output: '["lint","code","love","you"]' },
        ],
        starterCode: {
          python: `class Codec:\n    def encode(self, strs: list[str]) -> str:\n        res = ""\n        for s in strs:\n            res += str(len(s)) + "#" + s\n        return res\n\n    def decode(self, s: str) -> list[str]:\n        res, i = [], 0\n        while i < len(s):\n            j = s.find("#", i)\n            length = int(s[i:j])\n            res.append(s[j + 1 : j + 1 + length])\n            i = j + 1 + length\n        return res`,
          java: `public class Codec {\n    public String encode(List<String> strs) { return ""; }\n    public List<String> decode(String s) { return new ArrayList<>(); }\n}`,
          cpp: `class Codec {\npublic:\n    string encode(vector<string>& strs) { return ""; }\n    vector<string> decode(string s) { return {}; }\n};`,
        },
        solutionHint: 'Prefix each string with its length followed by a delimiter like "#".',
      },
      {
        id: 'trapping-rain-water',
        number: 8,
        title: 'Trapping Rain Water',
        difficulty: 'Hard',
        tag: 'Two Pointers / Stack',
        accuracy: '48% Acc.',
        status: 'pending',
        companies: ['Uber', 'Meta', 'Amazon'],
        description: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
        examples: [
          { input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' },
        ],
        starterCode: {
          python: `class Solution:\n    def trap(self, height: list[int]) -> int:\n        if not height: return 0\n        l, r = 0, len(height) - 1\n        max_l, max_r = height[l], height[r]\n        ans = 0\n        while l < r:\n            if max_l < max_r:\n                l += 1\n                max_l = max(max_l, height[l])\n                ans += max_l - height[l]\n            else:\n                r -= 1\n                max_r = max(max_r, height[r])\n                ans += max_r - height[r]\n        return ans`,
          java: `class Solution {\n    public int trap(int[] height) {\n        // Two pointers implementation in O(1) space\n        return 0;\n    }\n}`,
          cpp: `class Solution {\npublic:\n    int trap(vector<int>& height) {\n        // Two pointers implementation\n        return 0;\n    }\n};`,
        },
        solutionHint: 'Maintain two pointers l and r with left_max and right_max to calculate water level without extra array storage.',
      },
    ],
  },
  {
    id: 'two-pointers-sliding-window',
    title: 'Two Pointers & Sliding Window',
    track: 'dsa',
    badge: 'Core Pattern • 10 Problems',
    badgeType: 'secondary',
    totalProblems: 10,
    completedProblems: 10,
    companies: ['Adobe', 'Salesforce', 'Atlassian'],
    description: 'Subarray boundaries, monotonic windows, shrinking conditions, and slow-fast pointers.',
    estHoursRemaining: 0,
    avgAccuracy: 92,
    problems: [],
  },
  {
    id: 'dynamic-programming',
    title: 'Dynamic Programming',
    track: 'dsa',
    badge: 'Advanced • 16 Problems',
    badgeType: 'tertiary',
    totalProblems: 16,
    completedProblems: 4,
    companies: ['Amazon', 'Flipkart', 'Goldman Sachs'],
    description: 'Memoization, bottom-up tabulation, 0/1 knapsack variants, and multidimensional state transitions.',
    estHoursRemaining: 8.0,
    avgAccuracy: 64,
    problems: [],
  },
  {
    id: 'trees-bst',
    title: 'Trees & Binary Search Trees',
    track: 'dsa',
    badge: 'High Frequency • 14 Problems',
    badgeType: 'primary',
    totalProblems: 14,
    completedProblems: 7,
    companies: ['Microsoft', 'Meta', 'Oracle'],
    description: 'DFS/BFS recursions, lowest common ancestor, diameter, and Morris traversal guarantees.',
    estHoursRemaining: 4.5,
    avgAccuracy: 78,
    problems: [],
  },
  {
    id: 'graphs',
    title: 'Graph Algorithms & Shortest Path',
    track: 'dsa',
    badge: 'Core Pattern • 12 Problems',
    badgeType: 'primary',
    totalProblems: 12,
    completedProblems: 5,
    companies: ['Google', 'Uber', 'Directi'],
    description: 'Dijkstra, Topological Sort, Disjoint Set Union (DSU), and Tarjan cycle detection.',
    estHoursRemaining: 5.0,
    avgAccuracy: 71,
    problems: [],
  },
  {
    id: 'quantitative-aptitude',
    title: 'Quantitative & Bayes Probability',
    track: 'aptitude',
    badge: 'Campus Placement • 20 Problems',
    badgeType: 'secondary',
    totalProblems: 20,
    completedProblems: 12,
    companies: ['TCS', 'Infosys', 'Amazon', 'Wipro'],
    description: 'Permutations, combinations, conditional probability, time-speed-distance shortcuts.',
    estHoursRemaining: 2.0,
    avgAccuracy: 88,
    problems: [],
  },
  {
    id: 'microservices-hashing',
    title: 'System Design & High Concurrency',
    track: 'system-design',
    badge: 'Architecture • 8 Modules',
    badgeType: 'tertiary',
    totalProblems: 8,
    completedProblems: 3,
    companies: ['Amazon', 'Uber', 'Atlassian'],
    description: 'Consistent hashing, rate limiters, distributed cache eviction, and idempotent APIs.',
    estHoursRemaining: 6.0,
    avgAccuracy: 75,
    problems: [],
  },
  {
    id: 'os-dbms',
    title: 'Operating Systems & DBMS Essentials',
    track: 'core-cs',
    badge: 'Foundational • 15 Modules',
    badgeType: 'default',
    totalProblems: 15,
    completedProblems: 11,
    companies: ['Microsoft', 'Cisco', 'Qualcomm'],
    description: 'Virtual memory paging, ACID transactions, B-Tree indices, and concurrency locks.',
    estHoursRemaining: 2.5,
    avgAccuracy: 90,
    problems: [],
  },
];

export const COMPANY_TRACKS: CompanyHiringTrack[] = [
  {
    id: 'amazon',
    name: 'Amazon',
    logo: 'shopping_bag',
    industry: 'Cloud & Consumer Tech',
    role: 'Product SDE',
    difficulty: 'High',
    avgCtc: '32 LPA',
    patternMatch: 85,
    cohortMatch: 68,
    description: "Evaluation pattern strictly mirrors Amazon's Bar Raiser pipeline: intense emphasis on 16 Leadership Principles, optimized Graph/Tree DP algorithms, and high-concurrency microservice design.",
    rounds: [
      {
        number: 1,
        title: 'Round 1: Online Assessment',
        type: 'completed',
        scoreBadge: 'Score: 100%',
        summary: '2 Coding Questions (HackerRank) + Amazon Work Simulation & Behavioral Survey.',
        duration: '90 mins',
        statusText: 'Verified Cleared',
      },
      {
        number: 2,
        title: 'Round 2: Technical DSA',
        type: 'active',
        currentFocusBadge: 'Current Focus • 18 high-yield questions remaining',
        summary: 'Live virtual pairing with Amazon Senior SDE. Live coding on Trees, Dijkstra/BFS Graphs, and Subarray Dynamic Programming with strict edge constraints.',
        duration: '60 mins live coding',
        statusText: 'Target Score ≥ 90%',
      },
      {
        number: 3,
        title: 'Round 3: System Design & HR',
        type: 'locked',
        summary: 'Low-Level Design (LLD), Object-Oriented Patterns (Factory/Observer), followed by Bar Raiser STAR-format Behavioral Leadership Principles.',
        duration: '60 mins',
        statusText: 'Unlocks after Round 2 Mock',
      },
    ],
    studyAssets: [
      {
        id: 'amazon-top-dsa',
        title: 'Top 20 Amazon DSA Questions',
        subtitle: 'Dynamic Programming & Trees',
        solvedText: '14 Solved',
        icon: 'terminal',
      },
      {
        id: 'amazon-lp-sheet',
        title: '16 Leadership Principles Cheat Sheet',
        subtitle: 'Customer Obsession & Ownership • STAR Framework',
        solvedText: 'High Impact',
        icon: 'auto_stories',
      },
    ],
    patternOverview: {
      frequency: '42%',
      targetPace: '25 min',
      avgDiff: 'Medium',
      questionMix: { easy: 15, medium: 50, hard: 35 },
      advisoryPill: 'Critical focus: Strict bounds check & non-allocating edge cases',
      vibePoints: [
        {
          title: 'HashMap Dominance for O(n)',
          description: 'Amazon evaluators look immediately for single-pass frequency maps or two-pass bucket solutions before brute-force nested iterations are ever considered.',
          icon: 'data_object',
          color: 'secondary',
        },
        {
          title: 'Leadership Principle: Frugality vs Speed',
          description: 'Be ready to verbally defend space tradeoffs (e.g., O(k) frequency space vs O(n) raw lookups). Explicitly ask about constraints to demonstrate Bias for Action.',
          icon: 'psychology',
          color: 'primary',
        },
        {
          title: 'Obsessive Edge-Case Stress Tests',
          description: 'Interviewers specifically test empty arrays, large continuous integer flows, duplicated minimums, and unicode character anagrams.',
          icon: 'warning',
          color: 'error',
        },
      ],
      testedPatterns: [
        {
          title: 'Frequency Counters & Maps',
          description: 'Top-K components, anagram grouping, multi-occurrence tracking.',
          matchPercentage: 95,
          problems: [
            { title: 'Top K Frequent Elements', diff: 'Med' },
            { title: 'Group Anagrams', diff: 'Med' },
          ],
        },
        {
          title: 'Sliding Window + Hash Table Cache',
          description: 'Continuous memory blocks with O(1) set presence lookups.',
          matchPercentage: 80,
          problems: [
            { title: 'Subarray Sum Equals K', diff: 'Med' },
            { title: 'Longest Consecutive Sequence', diff: 'Med' },
          ],
        },
        {
          title: 'Prefix & Suffix Array Aggregation',
          description: 'Cumulative space traversal without secondary division operations.',
          matchPercentage: 65,
          problems: [
            { title: 'Product of Array Except Self', diff: 'Med' },
          ],
        },
      ],
      recentTrend: {
        tag: 'Real-Time Intake',
        body: 'Recent Amazon campus hackathons and SDE assessments have pivoted towards Hybrid Hashing. Interviewers increasingly frame questions around logistics tracking: pairing HashMaps with Monotonic Queues for continuous inventory stream updates.',
        insight: 'Over 60% of candidates who passed Round 1 proactively mentioned memory allocation limits.',
      },
    },
  },
  {
    id: 'google',
    name: 'Google',
    logo: 'search',
    industry: 'Search, Ads & Cloud',
    role: 'Software Engineer L3/L4',
    difficulty: 'Very High',
    avgCtc: '38 LPA',
    patternMatch: 92,
    cohortMatch: 58,
    description: 'Deep emphasis on clean, optimal asymptotic complexity, clean code without library shortcuts, and edge cases for Graph algorithms and dynamic memory recursion.',
    rounds: [
      {
        number: 1,
        title: 'Round 1: Screening Technical DSA',
        type: 'completed',
        scoreBadge: 'Score: 95%',
        summary: '45 mins live Google Docs coding on Tree serialization & Interval scheduling.',
        duration: '45 mins',
        statusText: 'Verified Cleared',
      },
      {
        number: 2,
        title: 'Round 2: Onsite DSA (Round A)',
        type: 'active',
        currentFocusBadge: 'Current Focus • Graph & DSU specialization',
        summary: 'Deep dive into 2D Grid Shortest Path & Dijkstra optimizations.',
        duration: '45 mins live coding',
        statusText: 'Target Score ≥ 90%',
      },
      {
        number: 3,
        title: 'Round 3: Googleyness & System',
        type: 'locked',
        summary: 'Hypothetical behavioral ethics, navigating ambiguity, and scalable caching.',
        duration: '45 mins',
        statusText: 'Unlocks after Round 2',
      },
    ],
    studyAssets: [
      {
        id: 'google-top-dsa',
        title: 'Top 30 Google Graph & DP Problems',
        subtitle: 'Bipartite Graphs & Range Queries',
        solvedText: '18 Solved',
        icon: 'terminal',
      },
      {
        id: 'googleyness-prep',
        title: 'Googleyness & Ambiguity Framework',
        subtitle: 'Collaborative Reasoning Guidelines',
        solvedText: 'Core Guide',
        icon: 'psychology',
      },
    ],
  },
  {
    id: 'microsoft',
    name: 'Microsoft',
    logo: 'grid_view',
    industry: 'Enterprise Software & Azure',
    role: 'Software Engineer',
    difficulty: 'High',
    avgCtc: '28 LPA',
    patternMatch: 88,
    cohortMatch: 74,
    description: 'Emphasis on clean modular design, Linked Lists, Tree Traversals, and concurrency fundamentals for OS/memory management.',
    rounds: [
      {
        number: 1,
        title: 'Round 1: Codility Assessment',
        type: 'completed',
        scoreBadge: 'Score: 100%',
        summary: '3 questions on algorithmic arrays, string parsing, and boundary validation.',
        duration: '75 mins',
        statusText: 'Verified Cleared',
      },
      {
        number: 2,
        title: 'Round 2: Data Structures & LLD',
        type: 'active',
        currentFocusBadge: 'Current Focus • Trees & Concurrency',
        summary: 'Binary Tree serialization, LRU cache implementation, thread-safe queuing.',
        duration: '60 mins',
        statusText: 'Target Score ≥ 85%',
      },
      {
        number: 3,
        title: 'Round 3: AA (As Appropriate) Director Round',
        type: 'locked',
        summary: 'Project architecture discussion and team cultural alignment.',
        duration: '45 mins',
        statusText: 'Final Stage',
      },
    ],
    studyAssets: [
      {
        id: 'msft-trees',
        title: 'Microsoft High Frequency Trees & Lists',
        subtitle: 'Morris Traversal & Deep Copy with Random Pointer',
        solvedText: '12 Solved',
        icon: 'terminal',
      },
    ],
  },
  {
    id: 'uber',
    name: 'Uber',
    logo: 'directions_car',
    industry: 'Mobility & Marketplace Tech',
    role: 'Software Engineer I',
    difficulty: 'Very High',
    avgCtc: '36 LPA',
    patternMatch: 82,
    cohortMatch: 64,
    description: 'Heavy emphasis on spatial algorithms (QuadTrees, Geohash), Two Pointers (Trapping Rain Water), and real-time concurrency.',
    rounds: [
      {
        number: 1,
        title: 'Round 1: CodeSignal OA',
        type: 'completed',
        scoreBadge: 'Score: 840/850',
        summary: 'General Coding Assessment with strict speed benchmarks.',
        duration: '70 mins',
        statusText: 'Verified Cleared',
      },
      {
        number: 2,
        title: 'Round 2: Complex Two Pointers & Graphs',
        type: 'active',
        currentFocusBadge: 'Current Focus • Monotonic Stacks',
        summary: 'High-yield problems like Trapping Rain Water, Largest Rectangle in Histogram.',
        duration: '60 mins',
        statusText: 'In Progress',
      },
      {
        number: 3,
        title: 'Round 3: Distributed System Design',
        type: 'locked',
        summary: 'Design Ride-Matching Dispatch Engine or Surge Pricing Service.',
        duration: '60 mins',
        statusText: 'Unlocks next',
      },
    ],
    studyAssets: [
      {
        id: 'uber-dsa',
        title: 'Uber Core Two Pointers & Geohash',
        subtitle: 'Monotonic Stack & Window Bounds',
        solvedText: '9 Solved',
        icon: 'terminal',
      },
    ],
  },
];
